### ISSUE TITLE
ERROR: [0b756f00-9799-4b2d-a177-5522a1d781bb]: [update-hp]: [(id=04f9e17fd8961be6, index=3)]: Failed to execute python .sos/update-hp_3_2a91c17b.py

### ISSUE THREAD

**Issue by ben-sandham** [stephenslab/ipynb-website#15]
`INFO: update-hp (index=4) is completed.
ERROR: [0b756f00-9799-4b2d-a177-5522a1d781bb]: [update-hp]: [(id=04f9e17fd8961be6, index=3)]:
Failed to execute python .sos/update-hp_3_2a91c17b.py
exitcode=1, workdir=C:\Users\bsand\Documents\Data_Science\ipynb-website
---------------------------------------------------------------------------
[update-hp + update-nb + update-wf + upda]: 5 pending steps: Notebook to HTML converter, Pipeline to HTML converter, TOC Javascript updater, Search Javescript updater, Obsolete files remover
[default]: Exits with 1 pending step (default_4)`

**Comment by benjamin-sandham** [comment]
When performing Step 7 of the ipynb-website README Quick Start, I experienced this error and was wondering if you have any insight on this matter. 
`INFO: update-hp (index=4) is completed.
ERROR: [0b756f00-9799-4b2d-a177-5522a1d781bb]: [update-hp]: [(id=04f9e17fd8961be6, index=3)]:
Failed to execute python .sos/update-hp_3_2a91c17b.py
exitcode=1, workdir=C:\Users\bsand\Documents\Data_Science\ipynb-website
---------------------------------------------------------------------------
[update-hp + update-nb + update-wf + upda]: 5 pending steps: Notebook to HTML converter, Pipeline to HTML converter, TOC Javascript updater, Search Javescript updater, Obsolete files remover
[default]: Exits with 1 pending step (default_4)`

**Comment by ben-sandham** [comment]
Hi, I am curious if you have any insight regarding the error I encountered on Step 7 of the Quick Start guide for the ipynb-website repository.

**Comment by gaow** [comment]
@benjamin-sandham what happen if you run 

```
python .sos/update-hp_3_2a91c17b.py
```

under folder

```
C:\Users\bsand\Documents\Data_Science\ipynb-website
```

as prompted in the error message above? Although in principle it should work, we haven't tested it for Windows. But the message from that command should tell us more. Thanks!

**Comment by ben-sandham** [comment]
`
$ python .sos/update-hp_3_2a91c17b.py
Traceback (most recent call last):
  File ".sos/update-hp_3_2a91c17b.py", line 1274, in <module>
    get_sha1_files([('protected\\_index.ipynb', 'docs\\protected.html')], [], {'protected': 'protect_folder', 'protected\\protected_page.ipynb': 'protect_page'}, write = True)
  File ".sos/update-hp_3_2a91c17b.py", line 1205, in get_sha1_files
    for fn, p in zip(index_files + notebook_files, password) if p]
  File ".sos/update-hp_3_2a91c17b.py", line 1205, in <listcomp>
    for fn, p in zip(index_files + notebook_files, password) if p]
  File ".sos/update-hp_3_2a91c17b.py", line 1191, in protect_page
    content = open(page).readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'docs\\protected.html'
`
@gaow running that command produced a file not found error. I appreciate your assistance, I have not worked with a JNB framework like this.

**Comment by gaow** [comment]
We have now released a version executed via `docker`, which should help with this issue:

https://github.com/stephenslab/ipynb-website/releases/tag/v0.9.8
