### ISSUE TITLE
--no-input option

### ISSUE THREAD

**Issue by maxdevblock** [stephenslab/ipynb-website#18]
In previous version, I edited _release.sos_ to include the `--no-input` option to `jupyter nbconvert`, to render html pages without the code.

Is there such a feature in the new version?

Thank you!

**Comment by gaow** [comment]
> In previous version, I edited release.sos to include the --no-input option to jupyter nbconvert

@maxdevblock sorry did you sent in a pull request for this? I don't recall but if this is tested and proven to work then we can definitely add it back to the code.

**Comment by maxdevblock** [comment]
@gaow Hi. No I didn't pull a req.
You can see old _release.sos_ version with `--no-input` option here
https://github.com/maxdevblock/covid-19-website/blob/master/release.sos
lines `175` and `197`

**Comment by gaow** [comment]
@maxdevblock thanks for the feedback. I just updated the release script incorporating your changes with option `--hide-code` default to False. To use it you can add `--hide-code` to your release command. I have also updated the docker image as the current releases uses docker. You can get the latest via `docker pull gaow/jnbinder`. Please try it out and close this ticket if it works. Thanks!

**Comment by maxdevblock** [comment]
@gaow WOW, just tested, perfect.
Many thanks to you!

PS: I use your ipynb-website tool since 1 year for epidata.it, really saved my day.
