### ISSUE TITLE
RuntimeError: Not all files have been downloaded

### ISSUE THREAD

**Issue by sid-verma** [stephenslab/ipynb-website#4]
Since I don't have permissions to reopen an issue that was closed, I opened a new one.
I've updated the files from v0.9.2 and now I get the following error.
```
INFO: Executing default_0:
INFO: input:   []
INFO: output:   []
INFO: Executing default_1: build ipynb website ...
INFO: input:   []
INFO: Executing download-jnbinder:
INFO: input:   []
jnbinder-master.zip: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>:
ERROR: [6e0c763c-777f-4e32-ad59-f88a821d3fdf]: [download-jnbinder ['jnbinder-master/READ]: RuntimeError: Not all files have been downloaded
[setup-jnbinder]: 1 pending step: setup-jnbinder_0
[default]: 1 pending step: default_2
```
I'm kinda lost here, as I have not worked with jnbinder before. Thanks!

**Comment by gaow** [comment]
@sidv1993 I think the culprit is this line 

```
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>:
```

It indicates some download failure. Google this error message leads to some interesting posts suggesting possible issues with Python on Mac which I will later come back to comment on. 

But this should not happen because once you have cloned the repository you should have all files in place and there is no need to download anything. Could you confirm you are indeed working with the fully cloned repo?

**Comment by sid-verma** [comment]
@gaow Yes, I have cloned the entire repo. However, I have both Python 2.7 and Python 3.6 installed on my machine. If it is an issue with Python on Mac, then it could be due to the version conflict.

**Comment by gaow** [comment]
I am on the go right now. Will be back to my desk in 1hr. In the meantime could you please `cd` to `docs` folder, type `python3` in it, then type

```
from jnbinder import compare_versions
```
And report back here the error message?

**Comment by sidv1993** [comment]
Here is the error.
`Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from jnbinder import compare_versions
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sidverma/Documents/GitHub/blog/docs/jnbinder.py", line 5, in <module>
    from dateutil.parser import parse
ModuleNotFoundError: No module named 'dateutil'`

**Comment by sid-verma** [comment]
Sure. I ran the command and got ```ImportError: No module named dateutil.parser``` and running ```pip3 install python-dateutil``` solved it! Thanks @gaow and @pcarbo for the help!

**Comment by gaow** [comment]
Hmm it did not occur to me `dateutil.parser` requires separate installation! Thanks for catching this @sidv1993. I just updated the script to respond more properly to such missing module errors. There is no need to update on your end though, if it works for you.
